# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('idCard', models.AutoField(primary_key=True, serialize=False)),
                ('cardLevel', models.SmallIntegerField(default=1)),
                ('cardCount', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('idCardType', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=140)),
                ('rarity', models.SmallIntegerField(choices=[(0, 'Common'), (1, 'Rare'), (2, 'Epic')])),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('idDeck', models.AutoField(primary_key=True, serialize=False)),
                ('deckNum', models.PositiveSmallIntegerField()),
                ('cardID', models.ManyToManyField(to='app1.Card')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('idDevice', models.CharField(max_length=200)),
                ('username', models.CharField(blank=True, default='', max_length=40)),
                ('cardID', models.ManyToManyField(through='app1.Card', to='app1.CardType')),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to='app1.models.BazukaUser'),
        ),
        migrations.AddField(
            model_name='card',
            name='cardType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app1.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='app1.models.BazukaUser'),
        ),
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set([('user', 'deckNum')]),
        ),
        migrations.AlterIndexTogether(
            name='deck',
            index_together=set([('user', 'deckNum')]),
        ),
        migrations.AlterUniqueTogether(
            name='card',
            unique_together=set([('user', 'cardType')]),
        ),
        migrations.AlterIndexTogether(
            name='card',
            index_together=set([('user', 'cardType')]),
        ),
    ]
