# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
