# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-07 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardtype',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
