# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20160407_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='loseCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='trophy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='winCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
