# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 16:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_remove_user_basicuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='basicUser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
