# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 15:50
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20160419_1151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deck',
            unique_together=set([]),
        ),
        migrations.AlterIndexTogether(
            name='deck',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cardID',
        ),
        migrations.RemoveField(
            model_name='deck',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='rarity',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='Cardid',
            field=models.IntegerField(db_index=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deck1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), null=True, size=8),
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
