# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 19:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20160519_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deck1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=-1), blank=True, null=True, size=8),
        ),
    ]
