# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 09:37
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20160520_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deck1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[2, 3, 6, 7, 12, 14, 17, 18], null=True, size=8),
        ),
    ]
