# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-11 11:05
from __future__ import unicode_literals

import app1.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20160630_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPack',
            fields=[
                ('idPack', models.AutoField(primary_key=True, serialize=False)),
                ('packType', models.IntegerField(default=0)),
                ('unlockStartTime', models.IntegerField(default=-1)),
                ('packLeagueLevel', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='cardtype',
            old_name='name',
            new_name='cardName',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='cardLeagueLevel',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='cardRarity',
            field=models.SmallIntegerField(choices=[(0, 'Common'), (1, 'Rare'), (2, 'Epic')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kingHP',
            field=models.SmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='user',
            name='leagueLevel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='packCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='packCycle',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=app1.models.default_pack_cycle, size=6),
        ),
        migrations.AddField(
            model_name='rewardpack',
            name='packUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewardPacks', to='app1.User'),
        ),
    ]
