# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 09:43
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20160527_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deck1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[0, 3, 8, 11, 12, 13, 16, 18], null=True, size=8),
        ),
    ]
