# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 09:47
from __future__ import unicode_literals

import app1.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160527_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deck1',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=app1.models.default_deck_gen, null=True, size=8),
        ),
    ]
