# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 10:22
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20160720_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='packEmptySlots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[1, 1, 1, 1], size=4),
        ),
    ]
