# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-25 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20160725_1030'),
        ('app1', '0008_auto_20160721_1022'),
    ]

    operations = [
    ]
