# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-26 16:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion



class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20160725_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requiredCardCount', models.IntegerField(default=0)),
                ('donatedCardCount', models.IntegerField(default=0)),
                ('donators', django.contrib.postgres.fields.hstore.HStoreField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.User')),
            ],
        ),
    ]
