# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 12:59
from __future__ import unicode_literals

import app1.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20160527_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('idClan', models.AutoField(primary_key=True, serialize=False)),
                ('clanDescription', models.TextField(blank=True, max_length=140, null=True)),
                ('clanTag', models.CharField(db_index=True, default=app1.models.clan_tag_generator, max_length=10, unique=True)),
                ('clanLocation', models.CharField(blank=True, max_length=30, null=True)),
                ('clanMemberCount', models.IntegerField(default=0)),
                ('clanType', models.IntegerField(default=0)),
                ('clanMinimumTrophies', models.IntegerField(default=0)),
                ('clanScore', models.IntegerField(default=0)),
                ('totalDonation', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserClanData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('donate_count', models.IntegerField(default=0)),
                ('lastRequestTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='idDevice',
            new_name='deviceID',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='trophy',
            new_name='trophiesCount',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='cardID',
            new_name='userCards',
        ),
        migrations.AddField(
            model_name='user',
            name='totalDonations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clan',
            name='clanLeader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.models.BazukaUser'),
        ),
        migrations.AddField(
            model_name='user',
            name='userClan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='app1.Clan'),
        ),
    ]
