# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 06:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='cardType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.CardType'),
        ),
        migrations.AddField(
            model_name='donation',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Clan'),
        ),
        migrations.AddField(
            model_name='donation',
            name='startTime',
            field=models.IntegerField(default=1469689065),
        ),
    ]
