# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_clan_clanname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='clanName',
            field=models.CharField(max_length=30),
        ),
    ]
