# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-06 06:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20160728_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='black_list',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='waiting_list',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='backtory_userId',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clan',
            name='clanType',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Request'), (2, 'Invite Only')], default=0),
        ),
        migrations.AlterField(
            model_name='donation',
            name='startTime',
            field=models.IntegerField(default=1470464755),
        ),
        migrations.AlterField(
            model_name='userclandata',
            name='position',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Elder'), (2, 'Co-Leader'), (3, 'Leader')], default=0),
        ),
    ]
