# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-07 05:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20160806_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='backtory_group_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='clan',
            name='backtory_group_owner',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invitaion_list',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_clan_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AddField(
            model_name='userclandata',
            name='daily_donate_count',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='startTime',
            field=models.IntegerField(default=1470549552),
        ),
    ]
