# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20160807_0559'),
        ('app1', '0011_merge'),
    ]

    operations = [
    ]
