# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20160623_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clanData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.UserClanData'),
        ),
    ]
