# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20160807_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_clan_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='startTime',
            field=models.IntegerField(default=1470828994),
        ),
        migrations.AlterField(
            model_name='user',
            name='clanData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app1.UserClanData'),
        ),
    ]
