# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_user_clandata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclandata',
            name='position',
            field=models.IntegerField(choices=[(0, 'Member'), (1, 'Leader')], default=0),
        ),
    ]
