# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='startTime',
            field=models.IntegerField(default=1470560650),
        ),
        migrations.AlterField(
            model_name='user',
            name='clanData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='app1.UserClanData'),
        ),
    ]
