# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20160807_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='startTime',
            field=models.IntegerField(default=1470560865),
        ),
    ]
