# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20160623_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clan',
            name='clanMemberCount',
        ),
    ]
