# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20160810_1136'),
        ('app1', '0015_auto_20160807_0907'),
    ]

    operations = [
    ]
