# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-25 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_remove_clan_clanmembercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='clanLeader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.models.BazukaUser'),
        ),
    ]
