# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20160816_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='clan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='app1.Clan'),
        ),
    ]
