# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_clan_clanleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='clan',
            name='clanBadge',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
