# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_clan_clanbadge'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packType', models.IntegerField(default=0)),
                ('unlockStartTime', models.IntegerField()),
                ('packLevel', models.IntegerField()),
                ('packUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewardPacks', to='app1.User')),
            ],
        ),
    ]
